export enum CountryCode {
  UA = "UA",
  RU = "RU",
  OTHER = "OTHER",
}

export enum JobCode {
  UNEMPLOYED = "UNEMPLOYED",
  BLOGGER = "BLOGGER",
  JOURNALIST = "JOURNALIST",
  POLITICIAN = "POLITICIAN",
  MILITARY = "MILITARY",
  SINGER = "SINGER",
  ACTOR = "ACTOR",
  SPORTSMAN = "SPORTSMAN",
  OTHER = "OTHER",
}

export enum ViewOnWarCode {
  WITH_UKRAINE = "WITH_UKRAINE",
  WITH_ORKY = "WITH_ORKY",
  QUIET = "QUIET",
  PEACE_DEATH = "PEACE_DEATH",
}
