name: Validate Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-lint:
    name: esLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files within `super-linter`

      # For more information, see: https://github.com/github/super-linter
      - name: Lint Code
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tsc:
    name: TCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: egordm/gha-yarn-node-cache@v1
      - name: install yarn
        run: yarn install

      - name: Check Types
        uses: icrawl/action-tsc@v1
