name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # For more information, see: https://github.com/github/super-linter
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
#      - name: TSC actions
#        uses: stepek/tsc-action@1.0.0
#        with:
#          args: --noEmit
