name: Validate Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Check Types
        run: pnpm run checktype

      - name: Check Types
        uses: icrawl/action-tsc@v1

  esLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Lint
        run: SKIP_ENV_VALIDATION=true pnpm run lint
